name: rgb-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - requests
      - pillow
      - tqdm
      - ipykernel
      - opencv-python
      - imageio
      - earthengine-api
      - geemap
      - rasterio
      - pyproj
      - geopandas
      - geedim